language: node_js
workspaces:
  use:
    - build
stages: 
  - install-build
  - test 
node_js:
  - "12"
  - "4" 
before_script:
  - 'nvm exec node sh install-relevant-react.sh'
  - 'if [ -n "${KARMA-}" ]; then export CHROME_BIN=chromium-browser; export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi'
matrix: 
  fast_finish: true
  include:
    - stage: install-build
      workspaces:
        create:
          name: build
          paths:
            - ./
      node_js: "lts/*"
      env:
      install:
        - 'npm install'
      before_script:
        - 'npx lerna bootstrap'
      script:
        - 'npx lerna run build'
    - node_js: "lts/*"
      env: LINT=true
      stage: test
    - node_js: "8"
      env: REACT=16
      stage: test
    - node_js: "6"
      env: REACT=16
      stage: test
    - node_js: "lts/*"
      env: REACT=16.8.5 RENDERER=16.8.5
      stage: test
    - node_js: "lts/*"
      env: REACT=16.8.5 RENDERER=16.8.3
      stage: test
    - node_js: "lts/*"
      env: REACT=16.8.3
      stage: test
    - node_js: "lts/*"
      env: REACT=16.8 RENDERER=16.7
      stage: test
    - node_js: "lts/*"
      env: REACT=16.7 RENDERER=16.8
      stage: test
    - node_js: "lts/*"
      env: REACT=16.7 RENDERER=16.7
      stage: test
    - node_js: "lts/*"
      env: REACT=16.3 ADAPTER=16
      stage: test
    - node_js: "lts/*"
      env: REACT=15.3
      stage: test
