language: node_js
workspaces:
  use:
    - build
stages: 
  - install-build 
  - test 
node_js:
  - "12"
  - "4"  
before_script:
  - 'nvm exec node sh install-relevant-react.sh'
  - 'if [ -n "${KARMA-}" ]; then export CHROME_BIN=chromium-browser; export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi'
matrix: 
  fast_finish: true
  include:
    - stage: install-build 
      workspaces:
        create:
          name: build 
          paths:
            - ./
      node_js: "lts/*"
      env:
      install:
        - 'npm install'
      before_script:
        - 'npx lerna bootstrap'
      script:
        - 'npx lerna run build'
    - node_js: "lts/*"
      env: LINT=true
      stage: test 
    - node_js: "8"
      env: REACT=16
      stage: test
    - node_js: "6"
      env: REACT=16
      stage: test
    - node_js: "lts/*"
      env: REACT=16.8.5 RENDERER=16.8.5
      stage: test
    - node_js: "lts/*"
      env: REACT=16.8.5 RENDERER=16.8.3
      stage: test
    - node_js: "lts/*"
      env: REACT=16.8.3
      stage: test
    - node_js: "lts/*"
      env: REACT=16.8 RENDERER=16.7
      stage: test
    - node_js: "lts/*"
      env: REACT=16.7 RENDERER=16.8
      stage: test 
    - node_js: "lts/*"
      env: REACT=16.7 RENDERER=16.7
      stage: test
    - node_js: "lts/*"
      env: REACT=16.3 ADAPTER=16
      stage: test
    - node_js: "lts/*"
      env: REACT=15.3 
      stage: test  
    - node_js: "lts/*"
      env: REACT=15.2
      stage: test 
    - node_js: "lts/*"
      env: REACT=15.1 
      stage: test 
    - node_js: "lts/*"
      env: REACT=15.0
      stage: test
    - node_js: "6"
      env: KARMA=true REACT=0.13
      stage: test
    - node_js: "6"
      env: KARMA=true REACT=0.14
      stage: test
    - node_js: "6"
      env: KARMA=true REACT=15.4
      stage: test
    - node_js: "6"
      env: KARMA=true REACT=15
      stage: test
    - node_js: "6"
      env: KARMA=true REACT=16
      stage: test
  allow_failures:
    - node_js: "6"
      env: KARMA=true REACT=0.13
    - node_js: "6"
      env: KARMA=true REACT=0.14
    - node_js: "6"
      env: KARMA=true REACT=15.4
    - node_js: "6"
      env: KARMA=true REACT=15
    - node_js: "6"
      env: KARMA=true REACT=16
    - node_js: "lts/*"
      env: REACT=16.8.5 RENDERER=16.8.3
    - node_js: "lts/*"
      env: REACT=16.8 RENDERER=16.7
  exclude:
    - node_js: "6"
      env: REACT=0.13
env:
  - REACT=16.14
  - REACT=16.13
  - REACT=16.12
  - REACT=16.11
  - REACT=16.10
