$lang['en'] += array(
	'mintguide.title' => 'Befolgen Sie die Anleitung Ihres Peercoin-Clients, um mit dem Prägen anzufangen!',
	'mintguide.qt_step1' => 'Vergewissern Sie sich, dass Ihre Brieftasche mit einer guten Passphrase verschlüsselt ist. Schreiben Sie sich diese auf und bewahren Sie sie an einem sicheren Platz auf. Sollten Sie die Passphrase vergessen, dann verlieren Sie Ihre Münzen. Die "Encrypt Wallet"-Option (Brieftasche verschlüsseln) kann unter dem Reiter "Settings" (Einstellungen) in der Peercoin-QT Brieftaschen-Software gefunden werden.',
	'mintguide.qt_step2' => 'Um das Prägen zu starten, klicken auf "Help" (Hilfe) -> "Debug window" (Debug-Fenster) -> "Console" (Konsole) und geben Sie ein: <br><kbd>walletpassphrase abc 999999 true</kbd><br> Die Zeichenkette "abc" ist hierbei Ihre Passphrase und "999999" die Zeitdauer des Prägens in Sekunden. Sie können die Anzahl der Sekunden beliebig verändern. Aber normalerweise ist es am einfachsten, einen sehr großen Wert zu wählen. Sollte Ihre Passphrase Leerzeichen enthalten, dann setzen Sie am Anfang und Ende der Passphrase Anführungszeichen.',
	'mintguide.qt_step3' => 'Löschen Sie Ihre Passphrase mit der Tastenkombination Ctrl-L.',
	'mintguide.qt_step4' => 'Sie können überprüfen, ob Sie gerade prägen, in dem Sie einen Blick auf das Vorhängeschloss in der rechten unteren Ecke des Fensters der Brieftasche werfen. Wenige Augenblicke später sollte es offen sein. Wenn Sie den Mauszeiger über das Schloss platzieren, sollte "Wallet is encypted and currently unlocked for block minting only" (Brieftasche ist verschlüsselt und aktuell nur zur Blockprägung entsperrt) zu lesen sein.',
	'mintguide.peerunity' => 'Peerunity is a client developed by the Peercoin community. It has more features than the standard Peercoin v0.4 client, and also has an easier method for minting. It is available for Windows, Linux, and OS X. You can download it here and view the launch thread <a href="https://talk.peercoin.net/t/peerunity-v0-1-0-released-for-windows-linux-os-x/2455">here</a>.',
	'mintguide.peerunity_step1' => 'Vergewissern Sie sich, dass Ihre Brieftasche mit einer guten Passphrase verschlüsselt ist. Schreiben Sie sich diese auf und bewahren Sie sie an einem sicheren Platz auf. Sollten Sie die Passphrase vergessen, dann verlieren Sie Ihre Münzen. Die "Brieftasche verschlüsseln"-Option kann unter dem Reiter "Einstellungen" in Peerunity gefunden werden.',
	'mintguide.peerunity_step2' => 'Um das Prägen zu starten, klicken Sie einfach auf die "Unlock Wallet for Minting Only"-Schaltfläche (Brieftasche nur zum Prägen entsperren), geben Sie Ihre Passphrase ein und klicken Sie auf OK.',
	'mintguide.peerunity_step3' => 'Sie können überprüfen, ob Sie gerade prägen, in dem Sie einen Blick auf das Vorhängeschloss in der rechten unteren Ecke des Fensters der Brieftasche werfen. Wenige Augenblicke später sollte es offen sein. Wenn Sie den Mauszeiger über das Schloss platzieren, sollte "Wallet is encypted and currently unlocked for block minting only" (Brieftasche ist verschlüsselt und aktuell nur zur Blockprägung entsperrt) zu lesen sein.',

);
