$lang['en'] += array(
	'mintguide.title' => 'Sigua el guía correspondiente a su Peercoin client para comenzar a acuñar!',
	'mintguide.qt_step1' => 'Asegúrese de que su cartera se cifra con una buena contraseña. Escribe esto y mantenerlo en un lugar seguro; si se olvida la clave, perderá sus monedas. La opción de cifrado de la carpeta se puede encontrar bajo la pestaña de configuración en el programa de la cartera Peercoin-Qt.',
	'mintguide.qt_step2' => 'Para iniciar la acuñación de ir a ayudar a -> debug window -> consola y escriba: <br> <kbd> walletpassphrase abc 999999 true </ KBD> <br> donde "abc" es su frase de paso y "999999" es el tiempo que desea menta en el segundo. Puede cambiar la cantidad de tiempo para lo que quieras, pero es generalmente más fácil sólo para ponerlo en un número muy alto. Si entonces la frase de contraseña tiene espacios encerrar entre comillas.',
	'mintguide.qt_step3' => 'Limpia tu contraseña pulsando Ctrl-L.',
	'mintguide.qt_step4' => 'Usted puede comprobar que siguen acuñando mirando el pequeño candado en la esquina inferior derecha de la cliente. Después de unos momentos debería estar desbloqueada. Si pasas el ratón sobre él, debe decir "cartera se encriptados, y actualmente desbloqueado para su bloque de acuñación única".',
	'mintguide.peerunity' => 'Peerunity is a client developed by the Peercoin community. It has more features than the standard Peercoin v0.4 client, and also has an easier method for minting. It is available for Windows, Linux, and OS X. You can download it here and view the launch thread <a href="https://talk.peercoin.net/t/peerunity-v0-1-0-released-for-windows-linux-os-x/2455">here</a>.',
	'mintguide.peerunity_step1' => 'Asegúrese de que su cartera se cifra con una buena contraseña. Escribe esto y mantenerlo en un lugar seguro; si se olvida la clave, perderá sus monedas. La opción de cifrado de la carpeta se puede encontrar bajo la pestaña de configuración en el programa de la cartera Peerunity.',
	'mintguide.peerunity_step2' => 'Para iniciar la acuñación, simplemente pulse Configuración "Desbloquear cartera para acuñar Sólo" botón, introduzca su contraseña y pulse Aceptar.',
	'mintguide.peerunity_step3' => 'Usted puede comprobar que sigue acuñando, mirando el pequeño candado en la esquina inferior derecha de la cliente. Después de unos momentos debería ser desbloqueada. Si pasas el ratón sobre él, debe decir "cartera es encriptada, y actualmente desbloqueado para su bloque de acuñación única".',

);
