$lang['en'] += array(
	'mintguide.title' => 'Suivez le guide correspondant à votre client Peercoin pour commencer à frapper la monnaie !',
	'mintguide.qt_step1' => 'Assurez-vous que votre portefeuille est crypté avec une bonne phrase de passe. Écrivez-la quelque part et gardez-la en lieu sûr; si vous oubliez la phrase de passe vous perdrez vos pièces. L\'option de cryptage du portefeuille se trouve dans le menu des réglages du programme portefeuille Peercoin-Qt.',
	'mintguide.qt_step2' => 'Pour commencer à frapper la monnaie allez dans aide -> fenêtre de débogage -> console et entrez :
<br><kbd>walletpassphrase abc 999999 true</kbd><br> où "abc" est votre phrase de passe et "999999" est le nombre de secondes pendant lequel vous voulez frapper la monnaie. Vous pouvez changer le nombre de secondes à ce que vous voulez, mais il est généralement plus facile de juste mettre un très grand nombre. Si votre phrase de passe contient des espaces alors il faut la mettre entre guillemets.',
	'mintguide.qt_step3' => 'Effacez votre phrase de passe en appuyant sur Ctrl-L.',
	'mintguide.qt_step4' => 'Vous pouvez vérifier que vous êtes en train de frapper la monnaie en regardant le petit cadenas dans le coin en bas à droite du client. Après quelques secondes il devrait être ouvert. Si vous passez votre souris dessus, il devrait être écrit "Le porte-monnaie est chiffré et actuellement déverrouillé uniquement pour la frappe de monnaie".',
	'mintguide.peerunity' => 'Peerunity est un client développé par la communauté Peercoin. Il a plus de fonctionnalités que le client standard Peercoin v0.4, et dispose aussi d\'une méthode plus simple pour frapper la monnaie. Il est disponible pour Windows, Linux et OS X. Vous pouvez le télécharger ici et voir le fil de lancement <a href="https://talk.peercoin.net/t/peerunity-v0-1-0-released-for-windows-linux-os-x/2455">ici</a>.',
	'mintguide.peerunity_step1' => 'Assurez-vous que votre portefeuille est crypté avec une bonne phrase de passe. Écrivez-la quelque part et gardez-la en lieu sûr; si vous oubliez la phrase de passe vous perdrez vos pièces. L\'option de cryptage du portefeuille se trouve dans le menu des réglages de Peerunity.',
	'mintguide.peerunity_step2' => 'Pour commencer à frapper la monnaie, cliquez simplement sur le bouton "Déverrouiller le porte-monnaie pour la frappe de monnaie uniquement", entrez votre phrase de passe et cliquez sur OK.',
	'mintguide.peerunity_step3' => 'Vous pouvez vérifier que vous êtes en train de frapper la monnaie en regardant le petit cadenas dans le coin en bas à droite du client. Après quelques secondes il devrait être ouvert. Si vous passez votre souris dessus, il devrait être écrit "Le porte-monnaie est chiffré et actuellement déverrouillé uniquement pour la frappe de monnaie".',

);
