$lang['en'] += array(
	'mintguide.title' => 'Ikuti panduan yang sesuai dengan klien Peercoin Anda untuk mulai pencetakan!',
	'mintguide.qt_step1' => 'Pastikan dompet Anda dienkripsi dengan password yang baik. Catat ini dan menyimpannya di suatu tempat yang aman; jika Anda lupa kata sandi Anda akan kehilangan uang Anda. Pilihan enkripsi dompet dapat ditemukan di bawah tab pengaturan dalam program dompet Peercoin-Qt.',
	'mintguide.qt_step2' => 'Untuk memulai pencetakan pergi ke tombol membantu -> jendela debug -> konsol dan masukkan: <br> <kbd>walletpassphrase abc 999.999 true</kbd> <br> mana "abc" adalah password Anda dan "999999" adalah waktu dimana Anda ingin cetak dalam detik. Anda dapat mengubah jumlah waktu untuk apa pun yang Anda suka, tetapi biasanya paling mudah adalah mengaturnya pada angka yang sangat tinggi. Jika passphrase Anda memiliki ruang maka diapit dengan tanda kutip.',
	'mintguide.qt_step3' => 'Kosongkan password Anda dengan menekan Ctrl-L.',
	'mintguide.qt_step4' => 'Anda dapat memeriksa pencetakan Anda dengan melihat gembok kecil di sudut kanan bawah klien. Setelah beberapa saat itu harus menjadi terkunci. Jika Anda membawa mouse Anda di atasnya, itu harus mengatakan "Dompet ini encypted dan saat ini dibuka hanya untuk blok pencetakan".',
	'mintguide.peerunity' => 'Peerunity is a client developed by the Peercoin community. It has more features than the standard Peercoin v0.4 client, and also has an easier method for minting. It is available for Windows, Linux, and OS X. You can download it here and view the launch thread <a href="https://talk.peercoin.net/t/peerunity-v0-1-0-released-for-windows-linux-os-x/2455">here</a>.',
	'mintguide.peerunity_step1' => 'Pastikan dompet Anda dienkripsi dengan password yang baik. Catat ini dan menyimpannya di suatu tempat yang aman; jika Anda lupa kata sandi Anda akan kehilangan uang Anda. Pilihan enkripsi dompet dapat ditemukan di bawah tab pengaturan di Peerunity.',
	'mintguide.peerunity_step2' => 'Untuk memulai pencetakan, cukup tekan tombol "Aktifkan Dompet Hanya untuk Pencetakan", masukkan password Anda dan tekan OK.',
	'mintguide.peerunity_step3' => 'Anda dapat memeriksa pencetakan Anda dengan melihat gembok kecil di sudut kanan bawah klien. Setelah beberapa saat itu harus menjadi terkunci. Jika Anda membawa mouse Anda di atasnya, itu harus mengatakan "Dompet ini encypted dan saat ini dibuka hanya untuk blok pencetakan".',

);
