$lang['en'] += array(
	'mintguide.title' => 'Siga o manual correspondente ao seu cliente Peercoin para começar a criar moedas!',
	'mintguide.qt_step1' => 'Assegure-se que a sua carteira está protegida e encriptada por uma boa palavra-chave. Anote-a, guardando de seguida num local seguro; se esquecer-se da sua palavra-chave, perderá para sempre as suas moedas. A opção de ecriptação da carteira pode ser encontrada no separador Definições da carteira Peercoin-Qt.',
	'mintguide.qt_step2' => 'Para começar a criar moedas, ir para Ajuda -> Janela Depuração -> Consola e insira  <br><kbd>walletpassphrase abc 999999 true</kbd><br> onde "abc" é a sua palavra-chave e "999999" é o período para o qual pretende criar moedas, em segundos. Pode alterar o período de tempo para o que desejar, mas normalmente é mais fácil colocar um valor elevado. Se a sua palavra-chave tem espaços, deve colocar colocar aspas antes e depois.',
	'mintguide.qt_step3' => 'Limpe a sua palavra-chave pressionado Ctrl-L.',
	'mintguide.qt_step4' => 'Pode verificar se está criando moedas através da barra do canto inferior direito do cliente, num ícon semelhante a um cadeado. Após alguns momentos deve ficar desbloqueado. Se passar o rato por cima do icon deve mostrar a seguinte mensagem: "A carteira está encriptada e actualmente desbloqueada apenas para criação de moeda".',
	'mintguide.peerunity' => 'Peerunity is a client developed by the Peercoin community. It has more features than the standard Peercoin v0.4 client, and also has an easier method for minting. It is available for Windows, Linux, and OS X. You can download it here and view the launch thread <a href="https://talk.peercoin.net/t/peerunity-v0-1-0-released-for-windows-linux-os-x/2455">here</a>.',
	'mintguide.peerunity_step1' => 'Assegure-se que a sua carteira está protegida e encriptada por uma boa palavra-chave. Anote-a, guardando de seguida num local seguro; se esquecer-se da sua palavra-chave, perderá para sempre as suas moedas. A opção de ecriptação da carteira pode ser encontrada no separador Definições da carteira Peerunity.',
	'mintguide.peerunity_step2' => 'Para começar a criar moeda, basta clicar o botão "Desbloquear Carteira Apenas para Criação", inserir a sua palavra-chave e clicar em OK.',
	'mintguide.peerunity_step3' => 'Pode verificar se está criando moedas através da barra do canto inferior direito do cliente, num ícon semelhante a um cadeado. Após alguns momentos deve ficar desbloqueado. Se passar o rato por cima do icon deve mostrar a seguinte mensagem: "A carteira está encriptada e actualmente desbloqueada apenas para criação de moeda".',

);
