$lang['en'] += array(
	'mintguide.title' => 'Sundin ang mga gabay na nauukol sa iyong Peercoin client upang simulan ang minting!',
	'mintguide.qt_step1' => 'Tiyakin na ang iyong pitaka ay naka-encrypt gamit ang isang mahusay na passphrase. Isulat ito at itago ito sa isang lugar na ligtas; kung nakalimutan mo ang passphrase mawawala sa iyo ang iyong mga barya. Ang pagpipilian sa pag-encrypt na pitaka ay makikita sa ilalim ng tab na mga setting sa programang wallet Peercoin-Qt.',
	'mintguide.qt_step2' => 'Upang simulan ang minting pumunta sa pagtulong -> debug window -> aaluin at pumasok: <br><kbd>walletpassphrase abc 999999 true</kbd><br> kung saan ang "abc" ay iyong passphrase at "999999"  ay ang oras na nais mong mag-mint para sa ilang segundo. Maaari mong baguhin ang dami ng oras sa anumang nais mo, ngunit ito ay karaniwang pinakamadali lamang kung itakda sa isang napakataas na bilang. Kung ang iyong passphrase ay may puwang puwes ilakip ito sa mga panipi.',
	'mintguide.qt_step3' => 'I-clear ang iyong passphrase sa pamamagitan ng pagpindot sa Ctrl-L.',
	'mintguide.qt_step4' => 'Maaari mong tingnan na nagmi-minting ka sa pamamagitan ng pagtingin sa maliit na kandado sa ibabang kanang sulok ng kliyente. Pagkatapos ng ilang sandali dapat itong buksan. Kung itatapat mo ang mouse dito, dapat "Ang pitaka ay na-encypt at kasalukuyang bukas para sa block minting lamang" ang sasabihin nito.',
	'mintguide.peerunity' => 'Peerunity is a client developed by the Peercoin community. It has more features than the standard Peercoin v0.4 client, and also has an easier method for minting. It is available for Windows, Linux, and OS X. You can download it here and view the launch thread <a href="https://talk.peercoin.net/t/peerunity-v0-1-0-released-for-windows-linux-os-x/2455">here</a>.',
	'mintguide.peerunity_step1' => 'Tiyakin na ang iyong pitaka ay naka-encrypt gamit ang isang mahusay na passphrase. Isulat ito at itago sa isang lugar na ligtas; kung nakalimutan mo ang passphrase mawawala sa iyo ang iyong mga barya. Ang pagpipilian sa pag-encrypt ng pitaka ay makikita sa ilalim ng tab na mga setting sa Peerunity.',
	'mintguide.peerunity_step2' => 'Upang simulan ang minting, pindutin lamang ang "Buksan ang Pitaka para sa Minting lamang" na button, ipasok ang iyong passphrase at pindutin ang OK.',
	'mintguide.peerunity_step3' => 'Maaari mong tingnan na nagmi-minting ka sa pamamagitan ng pagtingin sa maliit na kandado sa ibabang kanang sulok ng kliyente. Pagkatapos ng ilang sandali dapat itong buksan. Kung itatapat mo ang mouse dito, dapat "Ang pitaka ay na-encypt at kasalukuyang bukas para sa block minting lamang" ang sasabihin nito.',

);
